config/routes.rb
Hundredmiles::Application.routes.draw do

  root 'static#index'
  get 'about' => 'static#about'

  get 'donate' => 'donate#index'
  post 'donate' => 'donate#donate'
  get 'donate/:username' => 'donate#users_donations'

  get 'thanks' =>'donate#thanks'

  namespace :admin do
    root 'admin_console#index'
    resources :users
    resources :donations

  end

  

end

app/models/donation.rb
class Donation < ActiveRecord::Base
  has_one :user

  def self.total_donations
    return self.sum('amount');
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  validates_uniqueness_of :username, :case_sensitive => false
end

app/controllers/admin/admin_console_controller.rb
class Admin::AdminConsoleController < ApplicationController
  #Need to remove this from git
  http_basic_authenticate_with name: "ryan", password: "O3aaq9es"

  def index

  end

end

app/controllers/admin/donations_controller.rb
class Admin::DonationsController < ApplicationController
  before_action :set_donation, only: [:show, :edit, :update, :destroy]
  #Ensure the user is authenticated
  http_basic_authenticate_with name: "ryan", password: "O3aaq9es"

  # GET /donations
  # GET /donations.json
  def index
    @donations = Donation.all
  end

  # GET /donations/1
  # GET /donations/1.json
  def show
  end

  # GET /donations/new
  def new
    @donation = Donation.new
  end

  # GET /donations/1/edit
  def edit
  end

  # POST /donations
  # POST /donations.json
  def create
    @donation = Donation.new(donation_params)

    respond_to do |format|
      if @donation.save
        format.html { redirect_to [:admin, @donation], notice: 'Donation was successfully created.' }
        format.json { render action: 'show', status: :created, location: @donation }
      else
        format.html { render action: 'new' }
        format.json { render json: @donation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /donations/1
  # PATCH/PUT /donations/1.json
  def update
    respond_to do |format|
      if @donation.update(donation_params)
        format.html { redirect_to @donation, notice: 'Donation was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @donation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /donations/1
  # DELETE /donations/1.json
  def destroy
    @donation.destroy
    respond_to do |format|
      format.html { redirect_to admin_donations_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_donation
      @donation = Donation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def donation_params
      params.require(:donation).permit(:user_id, :amount, :name, :transaction_number)
    end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  #Ensure the user is authenticated
  http_basic_authenticate_with name: "ryan", password: "O3aaq9es"

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to [:admin, @user], notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to admin_users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :password, :email)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/donate_controller.rb
class DonateController < ApplicationController

  def index
    @users = User.all
    render "donate/index", :locals => {:users => @users}
  end

  #POST function to process a donation
  #Will require the PayPal functionality
  def donate

  end

  def users_donations
    #Need to grab the user details
    username = params[:username]
    @user = User.where("lower(username) = ?", username.downcase).first

    render "users_donations", :locals => {:user => @user}
  end

  #GET Page called after a donation has been made
  def thanks
    respond_to do |format|
      format.html;
    end
  end

end

app/controllers/static_controller.rb
class StaticController < ApplicationController


  def index
    #Grab all of the donation (Only outputting 10 on the front page)
    @donations = Donation.all
    render "static/index", :locals => {:donations => @donations}
  end

end

app/helpers/admin_consol_helper.rb
module AdminConsolHelper
end

app/helpers/admin_console_helper.rb
module AdminConsoleHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/donate_helper.rb
module DonateHelper
end

app/helpers/donations_helper.rb
module DonationsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/admin_console/index.html.erb
<h1>Admin console</h1>
<ul>
  <li><h3>Member actions</h3></li>
  <li><a href="/admin/users/new">Add new user</a></li>
  <li><a href="/admin/users">Edit users</a></li>
</ul>
<ul>
  <li><h3>Blog post actions</h3></li>
  <li><a href="/admin/blogs/new">Add new blog post</a></li>
  <li><a href="/admin/blogs/">List blog posts</a></li>
</ul>

app/views/admin/users/_form.html.erb
<%= form_for [:admin, @user] do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', admin_user_path(@user) %> |
<%= link_to 'Back', admin_users_path %>

app/views/admin/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Password</th>
      <th>Email</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.password %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', admin_user_path(user) %></td>
        <td><%= link_to 'Edit', edit_admin_user_path(user) %></td>
        <td><%= link_to 'Destroy', admin_user_path(user), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_admin_user_path %>

app/views/admin/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_users_path %>

app/views/admin/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_admin_user_path(@user) %> |
<%= link_to 'Back', admin_users_path %>

app/views/donate/index.html.erb
<div>
  <h1>TOTAL £xxx.xx</h1>
</div>
<div>
  <h4>Hall of Fame</h4>
  <% @users.each do |t| %>
      <a href="/donate/<%= t.username %>"> <%= t.username %> £xx.xxx </a>
  <% end %>
</div>

app/views/donate/thanks.html.erb
<h1>You are amazing! Thanks a lot!</h1>

app/views/donate/users_donations.html.erb
<h1><%= user.username %></h1>
<h3><%= user.email %></h3>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>1st Bedworth does 100 Miles for 100 years</title>
        <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
        <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
        <%= csrf_meta_tags %>
    </head>
    <body>
        <header>
          <div>
            <div id="logo">
              <h1>1st Bedworth</h1>
              <h4>#100miles3days>100years</h4>
            </div>
            <div id="nav">
              <ul>
                <li><a href="/" class="active">Home</a></li>
                <li><a href="/donate">Donate</a></li>
                <li><a href="/progress">Progress</a></li>
                <li><a href="/blog">Blog</a></li>
              </ul>
            </div>
          </div>
        </header>
        <div id="container">
            <%= yield %>
        </div>
        <footer>

        </footer>
    </body>
</html>